##########################################################################
#Author:                     zisefeizhu
#QQ:                         2********0
#Date:                       2020-09-12
#FileName:                   namespace.yaml
#URL:                        https://www.cnblogs.com/zisefeizhu/
#Description:                The test script
#Copyright (C):              2020 All rights reserved
###########################################################################
apiVersion: v1
kind: Namespace
metadata:
  name: myweb
  labels:
    name: myweb
  
