apiVersion: v1
kind: Service
metadata:
  name: node-exporter-service
  namespace: mon
  labels:
    app: node-exporter-service
spec:
  ports:
    - name: http
      port: 9100
      nodePort: 31672
      protocol: TCP
  type: NodePort
  selector:
    app: node-exporter