apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: mon
spec:
  storageClassName: prometheus-storageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi