apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: __CI_PROJECT_NAME__
  namespace: __NAMESPACE__
spec:
  storageClassName: __CI_PROJECT_NAME__
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
